- conf/psc/l10n.yml
Email from contributors ML
> Dear community,
> 
> I hope this email finds you well. My name is Emanuel, and I am writing to express my interest in the l10n-switzerland repository. I recently noticed that the repository appears to be inactive, and as someone passionate about its purpose, I am eager to contribute to its revitalization.
> 
> I am writing to inquire about the current maintainers of the l10n-switzerland repository and to express my willingness to take on a role as a maintainer. The project's objectives align closely with my interests and skills, and I believe that by actively participating in its development, we can work together to ensure its continued growth and success.
> 
> I have successfully contributed to various OCA repositories in the past, and I am committed to …
> Add ecino as switzerland maintainer

- conf/repo/l10n.yml
[UPD] change default_branch to 17.0
> [UPD] change default_branch to 17.0

- conf/psc/intercompany.yml
proposing myself to maintain multi-company repo.
I developped the following modules :
- [res_company_active](https://github.com/OCA/multi-company/blob/16.0/res_company_active)
- [res_company_search_view](https://github.com/OCA/multi-company/blob/16.0/res_company_search_view)
- [res_company_code](https://github.com/OCA/multi-company/pull/475)
- [res_company_category](https://github.com/OCA/multi-company/pull/392)
- [pos_restaurant_multi_company](https://github.com/OCA/multi-company/pull/537)
- [product_category_company_favorite](https://github.com/OCA/multi-company/tree/12.0/product_category_company_favorite)
CC @JordiBForgeFlow
Thanks !
> [ADD] legalsylvain as member of intercompany maintainers

- conf/repo/operating.yml
Based on the newest branch with some modules in it
> [IMP] update default branch in operating-unit repo

- conf/repo/social.yml
This automation would hold all automation modules (Similar to marketing automation). I used social as it is related (it is used mainly with mails and so on)
@pedrobaeza
> Add automation repository

- conf/psc/l10n.yml
@OCA/local-italy-maintainers let me know what you think :smile:
> Help maintaining https://github.com/OCA/l10n-italy

- conf/psc/web.yml
> [ADD] web: add CarlosRoca13 as member

- conf/repo/fleet.yml
> Switch fleet to 16.0

- conf/psc/e-learning.yml
- conf/repo/e-learning.yml
@OCA/board This is the PSC and Repo necessary for the elearning platform
> [ADD] elarning REPO + PSC

- conf/psc/openupgrade.yml
CC : @pedrobaeza, @StefanRijnhart, @MiquelRForgeFlow, @hbrunn
> [ADD] legalsylvain + pedrobaeza + MiquelRForgeFlow as PSC representative of OpenUpgrade project

- conf/repo/connector.yml
- conf/repo/oca.yml
- conf/repo/queue.yml
Subset of https://github.com/OCA/repo-maintainer-conf/pull/41
> connector, connector-interfaces, queue: Add branch 18.0

- conf/psc/manufacturing.yml
Recurring contributor of OCA/manufacturing project
Merged PR : https://github.com/OCA/manufacture/pulls?q=is%3Apr+author%3AquentinDupont+is%3Aclosed+merged
pending PR : https://github.com/OCA/manufacture/pulls/quentinDupont
Thanks ! 
CC : @quentinDupont
> [ADD] quentinDupont as maintainer of OCA/manufacturing project

- conf/repo/web.yml
@simahawk we would like to backport some modules to V12. Could we get the branch created? Thanks! :)
> web-api: add 12.0 branch

- conf/psc/edi.yml
I propose myself to help merging approved PRs on EDI
@OCA/edi-maintainers
> [ADD] jbaudoux as maintainer of OCA/edi project

- conf/psc/crm.yml
- conf/psc/procurement.yml
- conf/psc/product.yml
Hello,
I propose myself to help merging PRs regarding some repositories, especially `sale-workflow`, `purchase-workflow`, `product-attribute`/`product-variant` etc.
@OCA/crm-sales-marketing-maintainers @OCA/procurement-purchase-maintainers @OCA/product-maintainers
> [ADD] sebalix as member to some PSC

- conf/psc/cooperative.yml
I'm not sure why I became member of this PSC, so removing myself.
> Remove sbidoul from cooperative PSC

- conf/psc/l10n.yml
Robin has no time for managing this repo. I suggest myself as discussed with @sbidoul .
> Replace robinkeunen by remytms for l10n-belgium

- conf/psc/sale.yml
- conf/repo/sale.yml
This repo will be used for addons developped to support sales blanket orders
> sale-blanket: add new repo and psc

- .github/workflows/static.yml
Fixes https://github.com/OCA/repo-maintainer-conf/issues/71
> [doc] Upgrade doc GH actions

- conf/psc/shopfloor-app.yml
- conf/repo/shopfloor.yml
Followup of https://github.com/OCA/repo-maintainer-conf/pull/66
> [ADD] Shopflor app repo + PSC

- conf/repo/mass-mailing.yml
Following the recent creation of OCA/mail and https://github.com/OCA/social/pull/1549#issuecomment-2654624575
> Add mass-mailing repo

- conf/psc/l10n.yml
- conf/repo/l10n.yml
Also update default branch to 18.0.
Hello,
I'm proposing @JordiBForgeFlow as USA localization maintainer. You can check the PRs in the repo to see that ForgeFlow has contributed a lot and is trying to push the localization to new versions. In order to coordinate, review and merge, Jordi would be a good addition to the PSC team.
@OCA/local-usa-maintainers
> [ADD] JordiBForgeFlow as l10n-usa maintainer

- conf/psc/board.yml
@simahawk 
The update script failed for README generation.
I propose to put president in representative and everyone in members.
> [FIX] Board members: Put everyone in members and president in representatives

- conf/repo/logistics.yml
Dedicated module for managing putaways (as we did a dedicated repo for managing reservations)
cc @sebalix @rousseldenis
> [ADD] Logistics Putaway repository on 18.0

- conf/psc/crowdfunding.yml
- conf/repo/crowdfunding.yml
add a repository and PSC for modules that make Odoo a crowdfunding platform
> [ADD] crowdfunding repo and psc

- conf/psc/l10n.yml
Update PSC members as agreed on Discord and the local event on 17.5.2025
> Update PSC Finland

- conf/psc/l10n.yml
- conf/repo/l10n.yml
Fixes #95
- Update Finland maintainer PSC
- Update Germany maintainer PSC
> Master finland and germany maintainer psc fix

- conf/psc/cim.yml
- conf/repo/cim.yml
We have developed a module named cim_channel, which addresses the requirements set by recent European regulations mandating organizations to provide an internal channel for reporting complaints and whistleblowing.
Following discussions with the community, we believe that a new repository is the appropriate path forward. We propose naming it Complaint and Infringement Management (CIM).
We have added the necessary entries under the conf and psc directories, and our company has been designated as the repository maintainer.
The source code is available at: https://github.com/MovalAgroingenieria/cim
> [ADD] Proposal new repository Complaint and Infringement Management (CIM)

- conf/psc/intercompany.yml
There is a good bunch of open PRs in the repository and work to do to align versions. I would like to help to move things faster.
> Propose myself as intercompany maintainer
