OCA/repo-maintainer-conf

conf/psc/field.yml, conf/psc/l10n.yml, conf/psc/management.yml
Here is his profile: @SMaciasOSI
=> [IMP] Add smaciasosi to Mexico

conf/psc/connector.yml, conf/psc/infrastructure.yml, conf/psc/intercompany.yml, conf/psc/l10n.yml, conf/psc/oca.yml, conf/psc/pos.yml, conf/psc/tools.yml, conf/psc/web.yml, conf/psc/website.yml
Hi all.
I have the feeling that the list of maintainers is not at all up to date. I mean, some people don't participate at all in the repo they're supposed to maintain, or even don't contribute at all to the OCA (review / comment / contribution / etc...).
Current PR : 
- remove @elicoidal, who passed away a few years ago.
- remove @OSguard, who left odoo ecosystem 6 years ago
I made a script to identify maintainers who hadn't had a single interaction on github in 1 year. (not a comment, not a commit). here is the list. do you mind if I make another PR to remove these people? Thanks ! 
- @albariera
- @Capriatto
- @carlosrve
- @CharlineDumontet
- @coodec
- @DayssamAgora
- @ddico
- @duanyp1991
- @Ehtaga
- @eugen-don
- @EvvFoxy
- @fblauer
- @FFernandez-PlanetaTIC
- @Fouad-AGORA
- @gmader
- …
=> [REF] remove inactive members (1/2)

conf/psc/accounting.yml, conf/psc/community.yml, conf/psc/connector.yml, conf/psc/core.yml, conf/psc/crm.yml, conf/psc/donation.yml, conf/psc/dotnet.yml, conf/psc/human.yml, conf/psc/intercompany.yml, conf/psc/l10n.yml, conf/psc/logistics.yml, conf/psc/management.yml, conf/psc/procurement.yml, conf/psc/product.yml, conf/psc/project.yml, conf/psc/role.yml, conf/psc/vertical.yml, conf/psc/web.yml
* Based on top of https://github.com/OCA/repo-maintainer-conf/pull/9. Please merge before the other one.
*  Remove people listed in the previous issue. except :
* @CharlineDumontet (recent member of oca-consultants)
* @Ylemoing (recent member of oca-consultants)
* @jgrandguillaume removed from all the psc, except the board one
**Removal :** 
* [REM] Remove @YannickB. (no activity since June 2022)
* [REM] Remove @stephankeller. (no activity since February 2016)
* [REM] Remove @sebastiken. (no activity since September 2021)
* [REM] Remove @rgarnau. (no activity since March 2018)
* [REM] Remove @redarouichi. (no activity since January 2016)
* [REM] Remove @RBelfiore. (no activity since April 2022)
* [REM] Remove @plamarche. (no activity since April 2016)
* [REM] Remove @okuryan. (no activity …
=> [REF] remove inactive members (2/2)

conf/psc/product.yml
Hi. 
Propose to add me as member of product-maintainers team.
Author of the following 7 modules : 
- product_standard_price_tax_included, product_uom_use_type, product_category_type, product_uom_po_domain, product_net_weight, product_uom_measure_type, product_print_category
Contribution in the following 3 modules : 
- product_pricelist_direct_print, product_price_history, base_product_mass_addition
Current PSC representative : @gurneyalex 
current members : @jjscarafia, @JordiBForgeFlow, @rousseldenis 
Thanks for your feedback.
=> [ADD] legalsylvain as member of product-maintainers

conf/psc/product.yml
Proposing Harald Panten (https://github.com/HaraldPanten) as PSC for Product repositories.
Our team has been actively involved as contributors to the OCA, consistently demonstrating our commitment to the community and its projects.
=> [ADD] HaraldPanten as member of product-maintainers

conf/psc/logistics.yml, conf/repo/logistics.yml
A new family of modules that serve as a weighing shopfloor assistant for bussiness workflows in which weighing the stock operations is a key process.
Please check @pedrobaeza @etobella 
cc @sergio-teruel @Tecnativa
Modules to become part of this repo (for the moment):
=> [ADD] stock-weighing repository

conf/repo/web.yml
Originated from this discussion https://github.com/OCA/product-attribute/pull/1645#discussion_r1654672188.
Similarly to `mis-builder-contrib` this repo should host modules that extend `web-api` features but they are not generic and not part of core set of modules.
=> Add web-api-contrib repo

conf/psc/l10n.yml
Hello OCA maintainers,
@renatonlima and myself would like to promote Antonio Neto @antoniospneto from the Brazilian Engenere company as a PSC for the `OCA/l10n-brazil` repo.
Antonio has been doing **excellent contributions** over the last 3 years: 
https://github.com/OCA/l10n-brazil/graphs/contributors
- over: 364+ quality commits
- 148+ merged PRs https://github.com/OCA/l10n-brazil/pulls?q=is%3Apr+is%3Amerged+author%3Aantoniospneto
- countless quality reviews
- authored a couple new modules
- contributed PRs on other OCA repos
- overall he helped a lot (fixed hard issues, found complex issues during reviews) with the l10n_br_fiscal module, the l10n_br_account module, the banking boleto/CNAB modules and many other modules.
- he has a good knowledge how open source works
- helped a lot …
=> [ADD] l10n/brazil: add antoniospneto as member

conf/repo/maintainer.yml
Shall we archive and remove https://github.com/OCA/runbot-addons too?
=> Remove archived repo maintainer-quality-tools

conf/psc/l10n.yml
@OCA/local-italy-maintainers let me know what you think 😄. Grazie
=> Help maintaining https://github.com/OCA/l10n-italy

conf/psc/mail.yml, conf/repo/mail.yml
As per [a suggestion from @pedrobaeza that received a lot of positive feedback](https://github.com/OCA/social/issues/1458#issuecomment-2427476407), here is the PR to create new repo `oca/mail` that will focus on addons related to odoo's messaging features
@simahawk
=> [ADD] mail repo + psc

conf/psc/logistics.yml
@OCA/logistics-maintainers 
After many years at this position and as I'm joining the board now, I'd like to pass the banner to someone else in order to get some fresh blood.
I'd like to propose Jacques-Étienne as he achieved a lot of successful logistics projects and has a great vision of advanced logistics flows. His knowledge will benefit (yet) current and future contributions and I'm sure his advices will enhance what we do in OCA.
Don't hesitate to give your review on this.
=> [CHG] Logistics PSC representative: Change to jbaudoux

conf/psc/connector.yml, conf/psc/queue.yml, conf/repo/queue.yml
The connector PSC is too broad. Maintainers of the queue project (like me) don't necessarily want to be PSC of, say, connector-ecommerce.
So I propose to split out a dedicated PSC for the oca/queue project.
=> Add dedicated PSC for oca/queue

conf/global.yml
This account is not used anymore.
=> Remove oca-travis

conf/psc/connector.yml
@alexis-via @nimarosa 
Seeing you're busy (https://github.com/OCA/connector-telephony/pull/323) and that we have now 2 customers where we're actively using SMS, I foresee in next months a lot of migrations-to-16 and new modules being proposed to the telephony module. I want to become PSC so that I can more readily merge them after review.
=> [ADD] thomaspaulb to connector-telephony

conf/repo/logistics.yml
@OCA/logistics-maintainers 
Before first PR's creation in 18.0 repository and because modules amount in that field are quite important, I suggest to create a separate repository for release channel management.
See: https://github.com/OCA/wms
=> [ADD] Logistics: Release Channel, Reservation and Shopfloor repositories

conf/psc/sale.yml, conf/repo/sale.yml
This repository provides addons for stock prebooking in sales orders. Unlike default Odoo, it enables stock reservation before order confirmation and integrates this feature into related processes.
=> [ADD] sale-prebook repository

conf/repo/bank.yml
Following the vote of the Banking PCS, we should now create the new bank-payment repository to host the modules that use account.payment.method.line.
=> Add bank-payment-alternative repository

conf/psc/core.yml
After many years as one of the Top 10 contributors on the OCA, I think I can opt for core contributor.
On average, I review 34 PRs every month and 13 are merged made by me. Also, as you can check on the graphs, my collaboration is consistent.
My work is not related to a single repository, as I work a lot of them:
- OWL (web, automation, VOIP)
- OpenUpgrade (mainly improve on speed)
- Accouting
- Maintenance
- EDI
=> Add myself as Core Maintainer

conf/psc/ai.yml, conf/repo/ai.yml
We would like to start working on it.
@OCA/board @pedrobaeza
=> Add AI repositories and PSC

conf/repo/edi.yml
Following the conversation held in this PR (https://github.com/OCA/edi/pull/1163#issuecomment-3069224131), I am proposing the opening of an EDI sub-repository for the ediversa supplier.
On the other hand, I've been reviewing the discussion about separating the EDI repository, but it was ultimately discarded (https://github.com/OCA/repo-maintainer-conf/pull/99). For my part, I see sense in creating sub-repositories, since otherwise, there would be a very large single repository. It makes sense to leave the EDI repository for generic things, and on the other hand, the sub-repositories for each supplier. For external searches, it's possibly better too.
=> [ADD] Edi Ediversa Repository
